export const US_STATES: { code: string; name: string }[] = [
  { code: "AL", name: "Alabama" },
  { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" },
  { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" },
  { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" },
  { code: "DE", name: "Delaware" },
  { code: "DC", name: "District of Columbia" },
  { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" },
  { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" },
  { code: "IL", name: "Illinois" },
  { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" },
  { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" },
  { code: "ME", name: "Maine" },
  { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" },
  { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" },
  { code: "MO", name: "Missouri" },
  { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" },
  { code: "NV", name: "Nevada" },
  { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" },
  { code: "NM", name: "New Mexico" },
  { code: "NY", name: "New York" },
  { code: "NC", name: "North Carolina" },
  { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" },
  { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" },
  { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" },
  { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" },
  { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" },
  { code: "VA", name: "Virginia" },
  { code: "WA", name: "Washington" },
  { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" },
  { code: "WY", name: "Wyoming" },
];

const STATE_BY_CODE = new Map(US_STATES.map((s) => [s.code, s.name]));

export function stateName(code: string): string | undefined {
  return STATE_BY_CODE.get(code.toUpperCase());
}

// ZIP3-prefix → state ranges (standard USPS prefix allocation). Good enough to save the
// visitor a step by guessing their state from a 5-digit zip; the field stays editable
// because prefix ranges have real edge cases (split/shared prefixes) this table won't catch.
const ZIP3_RANGES: { start: number; end: number; code: string }[] = [
  { start: 6, end: 9, code: "PR" },
  { start: 10, end: 27, code: "MA" },
  { start: 28, end: 29, code: "RI" },
  { start: 30, end: 38, code: "NH" },
  { start: 39, end: 49, code: "ME" },
  { start: 50, end: 59, code: "VT" },
  { start: 60, end: 69, code: "CT" },
  { start: 70, end: 89, code: "NJ" },
  { start: 100, end: 149, code: "NY" },
  { start: 150, end: 196, code: "PA" },
  { start: 197, end: 199, code: "DE" },
  { start: 200, end: 205, code: "DC" },
  { start: 206, end: 219, code: "MD" },
  { start: 220, end: 246, code: "VA" },
  { start: 247, end: 268, code: "WV" },
  { start: 270, end: 289, code: "NC" },
  { start: 290, end: 299, code: "SC" },
  { start: 300, end: 319, code: "GA" },
  { start: 320, end: 349, code: "FL" },
  { start: 350, end: 369, code: "AL" },
  { start: 370, end: 385, code: "TN" },
  { start: 386, end: 397, code: "MS" },
  { start: 398, end: 399, code: "GA" },
  { start: 400, end: 427, code: "KY" },
  { start: 430, end: 459, code: "OH" },
  { start: 460, end: 479, code: "IN" },
  { start: 480, end: 499, code: "MI" },
  { start: 500, end: 528, code: "IA" },
  { start: 530, end: 549, code: "WI" },
  { start: 550, end: 567, code: "MN" },
  { start: 570, end: 577, code: "SD" },
  { start: 580, end: 588, code: "ND" },
  { start: 590, end: 599, code: "MT" },
  { start: 600, end: 629, code: "IL" },
  { start: 630, end: 658, code: "MO" },
  { start: 660, end: 679, code: "KS" },
  { start: 680, end: 693, code: "NE" },
  { start: 700, end: 714, code: "LA" },
  { start: 716, end: 729, code: "AR" },
  { start: 730, end: 749, code: "OK" },
  { start: 750, end: 799, code: "TX" },
  { start: 800, end: 816, code: "CO" },
  { start: 820, end: 831, code: "WY" },
  { start: 832, end: 838, code: "ID" },
  { start: 840, end: 847, code: "UT" },
  { start: 850, end: 865, code: "AZ" },
  { start: 870, end: 884, code: "NM" },
  { start: 885, end: 885, code: "TX" },
  { start: 889, end: 898, code: "NV" },
  { start: 900, end: 961, code: "CA" },
  { start: 967, end: 968, code: "HI" },
  { start: 970, end: 979, code: "OR" },
  { start: 980, end: 994, code: "WA" },
  { start: 995, end: 999, code: "AK" },
];

export function stateFromZip(zip: string): string | undefined {
  const digits = zip.replace(/\D/g, "");
  if (digits.length < 3) return undefined;
  const prefix = Number.parseInt(digits.slice(0, 3), 10);
  const match = ZIP3_RANGES.find((r) => prefix >= r.start && prefix <= r.end);
  return match && STATE_BY_CODE.has(match.code) ? match.code : undefined;
}
