import type { MetadataRoute } from "next";
import { siteConfig } from "@/lib/site-config";
import { US_STATES } from "@/lib/us-states";
import { CONDITIONS } from "@/lib/condition-facts";
import { MEDICATIONS } from "@/lib/medication-facts";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = `https://${siteConfig.domain}`;
  const routes = [
    "",
    "/get-quote",
    "/final-expense-insurance",
    "/guides",
    "/coverage-by-state",
    "/pre-existing-conditions",
    "/pre-existing-conditions/can-you-be-denied",
    "/pre-existing-conditions/no-waiting-period",
    "/pre-existing-conditions/prescriptions",
    "/privacy",
    "/terms",
    "/disclaimer",
    "/tcpa-consent",
    "/do-not-call",
  ];
  const guideRoutes = [
    "/avoiding-scams",
    "/avoiding-scams/agent-fraud",
    "/avoiding-scams/independent-vs-captive-vs-direct",
    "/avoiding-scams/policy-churning",
    "/avoiding-scams/scam-calls-targeting-seniors",
    "/avoiding-scams/truth-about-insurance-ads",
    "/avoiding-scams/verify-a-company-is-legitimate",
    "/cash-value-life-insurance",
    "/celebration-of-life",
    "/does-life-insurance-cover-suicide",
    "/dying-without-life-insurance",
    "/employer-vs-individual-life-insurance",
    "/final-expense-insurance-cost",
    "/final-expense-insurance-cost/5000",
    "/final-expense-insurance-cost/10000",
    "/final-expense-insurance-cost/15000",
    "/final-expense-insurance-cost/20000",
    "/final-expense-insurance-cost/25000",
    "/final-expense-insurance-cost/30000",
    "/final-expense-insurance-cost/40000",
    "/final-expense-insurance-for",
    "/final-expense-insurance-for/child",
    "/final-expense-insurance-for/grandparents",
    "/final-expense-insurance-for/parents",
    "/final-expense-insurance-for/sibling",
    "/final-expense-insurance-for/spouse",
    "/final-expense-insurance-in-your-50s",
    "/final-expense-insurance-in-your-60s",
    "/final-expense-insurance-in-your-70s",
    "/final-expense-insurance-in-your-80s",
    "/final-expense-insurance-vs-whole-life-insurance",
    "/final-expense-insurance/biggest-mistakes",
    "/final-expense-insurance/buy-online",
    "/final-expense-insurance/cremation-coverage",
    "/final-expense-insurance/is-it-worth-it",
    "/final-expense-vs-term-life",
    "/funeral-cost",
    "/funeral-cost/burial-vs-cremation",
    "/funeral-cost/casket-cost",
    "/funeral-cost/cemetery-plot-cost",
    "/funeral-cost/cremation-cost",
    "/funeral-cost/direct-cremation",
    "/funeral-cost/funeral-financial-assistance",
    "/funeral-cost/green-burial",
    "/funeral-cost/headstone-cost",
    "/funeral-cost/prepaid-funeral-plans",
    "/funeral-cost/what-to-expect",
    "/guaranteed-issue-life-insurance",
    "/hidden-costs-of-dying",
    "/how-to-choose-a-company",
    "/how-underwriting-works",
    "/is-life-insurance-taxable",
    "/level-vs-graded-vs-modified",
    "/level-vs-graded-vs-modified/graded-benefit",
    "/level-vs-graded-vs-modified/level-benefit",
    "/level-vs-graded-vs-modified/modified-benefit",
    "/life-insurance-for-children",
    "/life-insurance-glossary",
    "/life-insurance-riders",
    "/life-insurance-vs-accidental-death-insurance",
    "/life-insurance-vs-crowdfunding",
    "/life-insurance-vs-savings-account",
    "/managing-your-policy",
    "/managing-your-policy/beneficiary-dies-before-you",
    "/managing-your-policy/borrow-from-policy",
    "/managing-your-policy/cancel-policy",
    "/managing-your-policy/change-beneficiary",
    "/managing-your-policy/claim-denied",
    "/managing-your-policy/contestability-period",
    "/managing-your-policy/find-a-lost-policy",
    "/managing-your-policy/how-long-a-claim-takes-to-pay",
    "/managing-your-policy/how-to-file-a-claim",
    "/managing-your-policy/missed-premium-payment",
    "/multiple-life-insurance-policies",
    "/reduce-funeral-costs",
    "/traditional-funeral-vs-direct-burial",
    "/what-does-a-funeral-director-do",
    "/what-is-a-beneficiary",
    "/what-is-a-death-benefit",
    "/what-is-whole-life-insurance",
    "/whole-life-vs-universal-life",
  ];
  const stateRoutes = US_STATES.map((s) => `/coverage-by-state/${s.code.toLowerCase()}`);
  const conditionRoutes = CONDITIONS.map((c) => `/pre-existing-conditions/${c.slug}`);
  const medicationRoutes = MEDICATIONS.map((m) => `/pre-existing-conditions/prescriptions/${m.slug}`);
  return [...routes, ...guideRoutes, ...stateRoutes, ...conditionRoutes, ...medicationRoutes].map((route) => ({
    url: `${base}${route}`,
    lastModified: new Date(),
  }));
}
